wms-server:
    name: geomet-weather
    url: https://geo.wxod-dev.cmc.ec.gc.ca/geomet
    layers: [
        RADAR_1KM_RRAI,
        RADAR_1KM_RDBR,
        RADAR_1KM_RSNO,
        RADAR_COVERAGE_RRAI,
        GDPS.ETA_TT,
        GDPS.ETA_UU,
        GDPS.ETA_NT,
        HRDPS.CONTINENTAL_TT,
        HRDPS.CONTINENTAL_HR,
        RADAR_COVERAGE_RRAI.INV,
        HRDPS.CONTINENTAL_TD,
        GDPS.ETA_RT,
        HRDPS.CONTINENTAL_NT,
        GDPS.ETA_SD,
        HRDPS.CONTINENTAL_PR,
        GDPS.ETA_PR,
        GDPS.ETA_HR,
        HRDPS.CONTINENTAL_WGE,
        RDPS.ETA_SD,
        HRDPS.CONTINENTAL.DIAG_PTYPE,
        HRDPS.CONTINENTAL_PN-SLP,
        RDPS.ETA_NT,
        RDPS.ETA_SN,
        GDPS.ETA_WSPD,
        RDPS.ETA_TT,
        CGSL.ETA_ICEC,
        GDPS.ETA_SN,
        RDPS.DIAG_NW_PT1H,
        RDPA.6F_PR,
        GDPS.ETA_WD,
        RDPS.ETA_WGE,
        RDPS.ETA_PR,
        GDPS.ETA_RN,
        GDPS.ETA_WGE,
        RDPS.ETA_PN,
        REPS.DIAG.3_PRMM.ERGE1,
        REPS.DIAG.3_PRMM.ERGE5,
        REPS.DIAG.3_PRMM.ERMEAN,
        RDPS.ETA_RT
    ]
]
